name: Close Stale Discussions

permissions:
  discussions: read

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  close-stale-discussions:
    runs-on: ubuntu-latest

    steps:
      - name: Run StaleSweeper
        uses: steffen-karlsson/stalesweeper@v1.1.0
        with:
          days-before-close: '1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
